export interface ProductItem {
  id: string;
  number: string;
  name: string;
  category: 'हिरे व सोलिटेअर' | 'सोन्याचे दागिने' | 'उत्कृष्ट दागिने' | 'रोजचे दागिने';
  tagline: string;
  description: string;
  metal: string;
  gemstone: string;
  image: string;
  aspect: 'tall' | 'wide' | 'standard' | 'portrait';
}

export const SITE_CONFIG = {
  // ब्रँड माहिती
  brandName: "व्ही बी माकणीकर",
  brandNameEn: "V. B. Makneekar",
  brandMonogram: "VBM",
  tagline: "जिथे परंपरा भेटते अद्वितीय दागिन्यांशी",
  subTagline: "पिढ्यानपिढ्या जपलेल्या सौंदर्याची साक्ष देणारे हस्तनिर्मित दागिने.",

  contact: {
    phone: "7410105757",
    displayPhone: "+91 74101 05757",
    whatsappNumber: "7410105757",
    whatsappNumber2: "8149220394",
    email: "kshirsagarshrihari111@gmail.com",
    address: "भुसार लाईन, भांडे गल्ली, लातूर",
    addressEn: "Bhusar Line, Bhande Galli, Latur",
  },

  products: [
    {
      id: "product-1",
      number: "01",
      name: "Gold Antique Bangles",
      category: "सोन्याचे दागिने",
      tagline: "पारंपारिक नक्षीकाम असलेले कडे",
      description: "२२ कॅरेट सोन्याचे पारंपारिक नक्षीकाम असलेले आणि सुंदर फुलांची रचना असलेले कडे.",
      metal: "२२ कॅरेट पिवळे सोने",
      gemstone: "कोणतेही नाही",
      image: "/images/product-01.png",
      aspect: "tall",
    },
    {
      id: "product-2",
      number: "02",
      name: "Diamond Layered Necklace",
      category: "हिरे व सोलिटेअर",
      tagline: "भव्य आणि आकर्षक डायमंड नेकलेस",
      description: "दोन पदरी डायमंड नेकलेस ज्यामध्ये उत्कृष्ट हिऱ्यांची सजावट आणि ड्रॉप पेंडंट आहे.",
      metal: "१८ कॅरेट पांढरे सोने",
      gemstone: "व्हीव्हीएस डायमंड्स",
      image: "/images/product-02.png",
      aspect: "portrait",
    },
    {
      id: "product-3",
      number: "03",
      name: "Diamond Choker Set",
      category: "हिरे व सोलिटेअर",
      tagline: "क्लासिक डायमंड चोकर",
      description: "प्रशस्त डायमंड आणि पांढऱ्या सोन्याचा चोकर, लग्नसराईसाठी उत्तम निवड.",
      metal: "१८ कॅरेट पांढरे सोने",
      gemstone: "डायमंड्स",
      image: "/images/product-03.png",
      aspect: "wide",
    },
    {
      id: "product-4",
      number: "04",
      name: "Emerald Diamond Choker",
      category: "उत्कृष्ट दागिने",
      tagline: "पाचू आणि हिऱ्यांनी सजलेला चोकर",
      description: "मध्यभागी आकर्षक पाचू आणि सभोवताली हिऱ्यांची कलाकुसर असलेला भव्य चोकर.",
      metal: "१८ कॅरेट पांढरे सोने",
      gemstone: "पाचू आणि हिरे",
      image: "/images/product-04.png",
      aspect: "wide",
    },
    {
      id: "product-5",
      number: "05",
      name: "Sapphire Diamond Belt",
      category: "उत्कृष्ट दागिने",
      tagline: "राजेशाही नीलम आणि डायमंड कंबरपट्टा",
      description: "सुंदर निळे नीलम आणि चमकदार हिऱ्यांनी सजलेला पारंपरिक आणि राजेशाही कंबरपट्टा.",
      metal: "१८ कॅरेट पांढरे सोने",
      gemstone: "नीलम (Sapphire) आणि हिरे",
      image: "/images/product-05.png",
      aspect: "wide",
    },
    {
      id: "product-6",
      number: "06",
      name: "Diamond Drop Earrings",
      category: "हिरे व सोलिटेअर",
      tagline: "आकर्षक डायमंड ड्रॉप इयररिंग्ज",
      description: "पांढऱ्या सोन्यात जडवलेले अप्रतिम डायमंड ड्रॉप इयररिंग्ज, खास प्रसंगांसाठी.",
      metal: "१८ कॅरेट पांढरे सोने",
      gemstone: "हिरे",
      image: "/images/product-06.png",
      aspect: "tall",
    },
    {
      id: "product-7",
      number: "07",
      name: "Kundan Polki Necklace",
      category: "सोन्याचे दागिने",
      tagline: "हिरव्या मण्यांचा कुंदन नेकलेस",
      description: "हिरवे मणी आणि अनकट पोलकी कुंदनने सजलेला पारंपारिक नेकलेस.",
      metal: "२२ कॅरेट पिवळे सोने",
      gemstone: "पोलकी आणि पाचू मणी",
      image: "/images/product-07.png",
      aspect: "portrait",
    },
    {
      id: "product-8",
      number: "08",
      name: "Navratna Polki Choker",
      category: "सोन्याचे दागिने",
      tagline: "रंगीबेरंगी रत्नांचा चोकर",
      description: "मोत्यांच्या झालरसह आणि रंगीत रत्नांनी जडलेला आकर्षक चोकर.",
      metal: "२२ कॅरेट पिवळे सोने",
      gemstone: "नवरत्न आणि मोती",
      image: "/images/product-08.png",
      aspect: "wide",
    },
    {
      id: "product-9",
      number: "09",
      name: "Antique Long Necklace",
      category: "सोन्याचे दागिने",
      tagline: "अँटिक सोन्याचा लांब हार",
      description: "मीनाकारी आणि पोलकीने सजलेला लांब हार, मोत्यांच्या गुंफणीसह.",
      metal: "२२ कॅरेट अँटिक सोने",
      gemstone: "पोलकी आणि मोती",
      image: "/images/product-09.png",
      aspect: "tall",
    },
    {
      id: "product-10",
      number: "10",
      name: "Peacock Motif Vaddanam",
      category: "सोन्याचे दागिने",
      tagline: "मोराची नक्षी असलेला कमरपट्टा",
      description: "सुंदर मोराची नक्षी आणि रत्नांनी जडवलेला राजेशाही कंबरपट्टा.",
      metal: "२२ कॅरेट पिवळे सोने",
      gemstone: "माणिक, पाचू आणि मोती",
      image: "/images/product-10.png",
      aspect: "wide",
    },
    {
      id: "product-11",
      number: "11",
      name: "Kundan Jhumka Earrings",
      category: "सोन्याचे दागिने",
      tagline: "मोत्यांच्या झालरसह कुंदन झुमके",
      description: "रंगीबेरंगी रत्ने आणि मोत्यांच्या लांब झालरसह पारंपारिक कुंदन झुमके.",
      metal: "२२ कॅरेट पिवळे सोने",
      gemstone: "कुंदन, मोती आणि माणिक",
      image: "/images/product-11.png",
      aspect: "tall",
    },
    {
      id: "product-12",
      number: "12",
      name: "Rose Gold Diamond Ring",
      category: "हिरे व सोलिटेअर",
      tagline: "रोझ गोल्ड डायमंड अंगठी",
      description: "रोझ गोल्डमध्ये जडवलेली सुंदर हिऱ्याची अंगठी.",
      metal: "१८ कॅरेट रोझ गोल्ड",
      gemstone: "हिरे",
      image: "/images/product-12.png",
      aspect: "standard",
    },
    {
      id: "product-13",
      number: "13",
      name: "Pearl Drop Earrings",
      category: "रोजचे दागिने",
      tagline: "मोत्याचे ड्रॉप इयररिंग्ज",
      description: "सोप्या आणि सुंदर डिझाईनचे मोत्याचे ड्रॉप इयररिंग्ज, रोजच्या वापरासाठी.",
      metal: "१८ कॅरेट पिवळे सोने",
      gemstone: "गोड्या पाण्याचे मोती",
      image: "/images/product-13.png",
      aspect: "standard",
    },
    {
      id: "product-14",
      number: "14",
      name: "Gold Chain Bracelet",
      category: "रोजचे दागिने",
      tagline: "सोन्याचे साखळी ब्रेसलेट",
      description: "रोजच्या वापरासाठी योग्य, हलके आणि सुंदर सोन्याचे ब्रेसलेट.",
      metal: "२२ कॅरेट पिवळे सोने",
      gemstone: "कोणतेही नाही",
      image: "/images/product-14.png",
      aspect: "wide",
    },
    {
      id: "product-15",
      number: "15",
      name: "Ruby Pendant Set",
      category: "उत्कृष्ट दागिने",
      tagline: "माणिक आणि हिऱ्यांचा पेंडंट सेट",
      description: "सुंदर माणिक आणि हिऱ्यांनी जडवलेला पेंडंट आणि इयररिंग्जचा सेट.",
      metal: "१८ कॅरेट पांढरे सोने",
      gemstone: "माणिक आणि हिरे",
      image: "/images/product-15.png",
      aspect: "portrait",
    },
    {
      id: "product-16",
      number: "16",
      name: "Traditional Gold Thushi",
      category: "सोन्याचे दागिने",
      tagline: "महाराष्ट्रीयन पारंपारिक ठुशी",
      description: "सोन्याच्या मण्यांनी गुंफलेली पारंपारिक महाराष्ट्रीयन ठुशी.",
      metal: "२२ कॅरेट पिवळे सोने",
      gemstone: "कोणतेही नाही",
      image: "/images/product-16.png",
      aspect: "wide",
    },
    {
      id: "product-17",
      number: "17",
      name: "Diamond Mangalsutra",
      category: "उत्कृष्ट दागिने",
      tagline: "डायमंड मंगळसूत्र",
      description: "आधुनिक डिझाईनचे हिऱ्यांनी जडवलेले मंगळसूत्र.",
      metal: "१८ कॅरेट पिवळे आणि पांढरे सोने",
      gemstone: "हिरे",
      image: "/images/product-17.png",
      aspect: "wide",
    },
    {
      id: "product-18",
      number: "18",
      name: "Gold Temple Earrings",
      category: "सोन्याचे दागिने",
      tagline: "पारंपारिक टेंपल डिझाईन इयररिंग्ज",
      description: "देवतेची मूर्ती आणि नक्षीकाम असलेले पारंपारिक सोन्याचे इयररिंग्ज.",
      metal: "२२ कॅरेट पिवळे सोने",
      gemstone: "माणिक आणि पाचू",
      image: "/images/product-18.png",
      aspect: "tall",
    },
    {
      id: "product-19",
      number: "19",
      name: "Platinum Solitaire Ring",
      category: "हिरे व सोलिटेअर",
      tagline: "प्लॅटिनम सोलिटेअर अंगठी",
      description: "प्लॅटिनममध्ये जडवलेली अप्रतिम गोल सोलिटेअर अंगठी.",
      metal: "९५० प्लॅटिनम",
      gemstone: "सोलिटेअर हिरा",
      image: "/images/product-19.png",
      aspect: "standard",
    },
    {
      id: "product-20",
      number: "20",
      name: "Emerald Studs",
      category: "रोजचे दागिने",
      tagline: "पाचूचे स्टड्स",
      description: "रोजच्या वापरासाठी योग्य, साधे आणि सुंदर पाचूचे स्टड्स.",
      metal: "१८ कॅरेट पिवळे सोने",
      gemstone: "पाचू",
      image: "/images/product-20.png",
      aspect: "standard",
    },
    {
      id: "product-21",
      number: "21",
      name: "Gold Goth Bangles",
      category: "सोन्याचे दागिने",
      tagline: "सोन्याच्या गोठ बांगड्या",
      description: "जाड आणि नक्षीदार सोन्याच्या गोठ बांगड्या.",
      metal: "२२ कॅरेट पिवळे सोने",
      gemstone: "कोणतेही नाही",
      image: "/images/product-21.png",
      aspect: "standard",
    },
    {
      id: "product-22",
      number: "22",
      name: "Polki Maang Tikka",
      category: "सोन्याचे दागिने",
      tagline: "पारंपारिक पोलकी मांग टिका",
      description: "वधूंसाठी खास पोलकी आणि मोत्यांनी सजलेला मांग टिका.",
      metal: "२२ कॅरेट पिवळे सोने",
      gemstone: "पोलकी आणि मोती",
      image: "/images/product-22.png",
      aspect: "portrait",
    },
    {
      id: "product-23",
      number: "23",
      name: "Diamond Tennis Bracelet",
      category: "हिरे व सोलिटेअर",
      tagline: "क्लासिक डायमंड टेनिस ब्रेसलेट",
      description: "हाताच्या सौंदर्यात भर घालणारे क्लासिक डायमंड टेनिस ब्रेसलेट.",
      metal: "१८ कॅरेट पांढरे सोने",
      gemstone: "हिरे",
      image: "/images/product-23.png",
      aspect: "wide",
    },
    {
      id: "product-24",
      number: "24",
      name: "Bridal Gold Choker",
      category: "सोन्याचे दागिने",
      tagline: "वधूचा सोन्याचा चोकर",
      description: "लग्नासाठी खास डिझाईन केलेला भव्य सोन्याचा चोकर.",
      metal: "२२ कॅरेट पिवळे सोने",
      gemstone: "माणिक आणि मोती",
      image: "/images/product-24.png",
      aspect: "portrait",
    },
    {
      id: "product-25",
      number: "25",
      name: "Sapphire Drop Pendant",
      category: "उत्कृष्ट दागिने",
      tagline: "नीलम ड्रॉप पेंडंट",
      description: "आकर्षक निळा नीलम आणि हिऱ्यांनी जडवलेले पेंडंट.",
      metal: "१८ कॅरेट पांढरे सोने",
      gemstone: "नीलम आणि हिरे",
      image: "/images/product-25.png",
      aspect: "tall",
    }
  ] as ProductItem[]
};
